spring:
    profiles:
        active:
        - dev

---
server:
    port: 8088
spring:
    profiles: dev
    application:
        name: servicecloud-dev

---
server:
    port: 8090
spring:
    profiles: test
    application:
        name: servicecloud-test