spring:
    profiles:
        active:
        - dev

---
server:
    port: 2002
spring:
    profiles: dev
    application:
        name: servicecloud-dev

---
server:
    port: 2030
spring:
    profiles: test
    application:
        name: servicecloud-test